const uav_param_config = 
{
    'uavs': 
    [
        {
            'name': 'Zagi',
            'mass': 1.56,
            'J_vector':  //vector of elements in the Intertial Matrix
            {
                'x':0.1147, //J_x or J_xx (Kg m^2)
                'y':0.0576, //J_y or J_yy (Kg m^2)
                'z':0.1712, //J_z or J_zz (Kg m^2)
                'xz':0.0015 //J_xz (Kg m^2)
            },
            'S':0.2589,  //Surface area of the wing (m^2)
            'b':1.4224,  //Wing span (m)
            'c':0.3302,  //Mean aerodynamic chord of the wing (m)
            'S_prop':0.0314,  //Area of the propeller (m^2)
            'k_motor':20,  //Constant that specifies the efficiency of the motor 
            'k_T_p':0,  //Constant determined experiment to determine the torque generated by propellor at different prop angular speeds
            'k_Omega':0,  //Constant to convert prop motor PWM commands to Prop Angular Speed
            'e':0.9,
            'C_arr':
            {
                'L_0':0.09167,  //Zeroth Order Longitudinal Coefficient of Alpha the Angle of Attack to Calculate Lift Coefficient
                'D_0':0.01631,  //Zeroth Order Longitudinal Coefficient of Alpha the Angle of Attack to Calculate Drag Coefficient
                'm_0':-0.02338, //Zeroth Order Longitudinal Coefficient of Alpha the Angle of Attack to Calculate Torque Coefficient
                'L_alpha':3.5016,  //First Order Longitudinal Coefficient of Alpha the Angle of Attack to Calculate Lift Coefficient
                'D_alpha':0.2108,  //First Order Longitudinal Coefficient of Alpha the Angle of Attack to Calculate Drag Coefficient
                'm_alpha':-0.5675, //First Order Longitudinal Coefficient of Alpha the Angle of Attack to Calculate Torque Coefficient
                'L_q':2.8932,
                'D_q':0,
                'm_q':-1.399,
                'L_delta_e':0.2724,
                'D_delta_e':0.3045,
                'm_delta_e':-0.3254,
                'prop':1.0,
                'D_p':0.0254,
                'Y_0':0,
                'l_0':0,
                'n_0':0,
                'Y_beta':-0.07359,
                'l_beta':-0.02854,
                'n_beta':-0.00040,
                'Y_p':0,
                'l_p':-0.3209,
                'n_p':-0.01297,
                'Y_r':0,
                'l_r':0.03066,
                'n_r':-0.00434,
                'Y_delta_a':0,
                'l_delta_a':0.1682,
                'n_delta_a':-0.00328
            },
            'M':50,
            'alpha_0':0.4712,
            'epsilon':0.1592
        },
        {
            'name': 'Aerosonode',
            'mass': 13.5,
            'J_vector':
            {
                'x':0.8244,
                'y':1.135,
                'z':1.759,
                'xz':0.1204
            },
            'S':0.55,
            'b':2.8956,
            'c':0.18994,
            'S_prop':0.2027,
            'rho':1.2682,
            'k_motor':80,
            'k_T_p':0,
            'k_Omega':0,
            'e':0.9,
            'C_arr':
            {
                'L_0':0.28,
                'D_0':0.03,
                'm_0':-0.02338,
                'L_alpha':3.45,
                'D_alpha':0.30,
                'm_alpha':-0.38,
                'L_q':0,
                'D_q':0,
                'm_q':-3.6,
                'L_delta_e':-0.36,
                'D_delta_e':0,
                'm_delta_e':-0.5,
                'prop':1.0,
                'D_p':0.0437,
                'n_delta_r':-0.032,
                'Y_0':0,
                'l_0':0,
                'n_0':0,
                'Y_beta':-0.98,
                'l_beta':-0.12,
                'n_beta':0.25,
                'Y_p':0,
                'l_p':-0.26,
                'n_p':0.022,
                'Y_r':0,
                'l_r':0.14,
                'n_r':-0.35,
                'Y_delta_a':0,
                'l_delta_a':0.08,
                'n_delta_a':0.06,
                'Y_delta_r':-0.17,
                'l_delta_r':0.105
            },
            'M':50,
            'alpha_0':0.4712,
            'epsilon':0.1592
        },
        {
            'name': 'Gemini'
        }
    ]
}

const g = 9.8;  //Acceleration Due To Gravity (m/s)
const rho = 1.2682;  // Air Density (Kg/m^3)

module.exports = {uav_param_config, g, rho};