const uav_param_config = 
{
    'uavs': 
    [
        {
            'name': 'Zagi',
            'mass': 1.56,             //Kg
            'V_s': 11.73565,          //m/s
            'J_vector':               //vector of elements in the Intertial Matrix
            {
                'x':0.1147,           //J_x or J_xx (Kg m^2)
                'y':0.0576,           //J_y or J_yy (Kg m^2)
                'z':0.1712,           //J_z or J_zz (Kg m^2)
                'xz':0.0015           //J_xz (Kg m^2)       
            },
            'S':0.2589,               //Surface area of the wing (m^2)
            'b':1.4224,               //Wing span (m)
            'c':0.3302,               //Mean aerodynamic chord of the wing (m)
            'S_prop':0.0314,          //Area of the propeller (m^2)
            'k_motor':20,             //Constant that specifies the efficiency of the motor
            'k_T_p':0,                //Constant determined experiment to determine the torque generated by propellor at different prop angular speeds
            'k_Omega':0,              //Constant to convert prop motor PWM commands to Prop Angular Speed
            'e':0.9,
            'C_arr':
            {
                'L_0':0.09167,        //Zeroth Order Longitudinal Derivative Coefficient of Alpha the Angle of Attack to Calculate Lift Coefficient
                'D_0':0.01631,        //Zeroth Order Longitudinal Derivative Coefficient of Alpha the Angle of Attack to Calculate Drag Coefficient
                'm_0':-0.02338,       //Zeroth Order Longitudinal Derivative Coefficient of Alpha the Angle of Attack to Calculate Torque Coefficient
                'L_alpha':3.5016,     //First Order  Longitudinal Derivative Coefficient of Alpha the Angle of Attack to Calculate Lift Coefficient
                'D_alpha':0.2108,     //First Order  Longitudinal Derivative Coefficient of Alpha the Angle of Attack to Calculate Drag Coefficient
                'm_alpha':-0.5675,    //First Order  Longitudinal Derivative Coefficient of Alpha the Angle of Attack to Calculate Torque Coefficient
                'L_q':2.8932,         //First Order  Longitudinal Derivative Coefficient of Pitch Rate to Calculate Lift Coefficient
                'D_q':0,              //First Order  Longitudinal Derivative Coefficient of Pitch Rate to Calculate Drag Coefficient
                'm_q':-1.399,         //First Order  Longitudinal Derivative Coefficient of Pitch Rate to Calculate Torque Coefficient
                'L_delta_e':0.2724,   //First Order  Longitudinal Derivative Coefficient of aeleron deflecion to Calculate Lift Coefficient
                'D_delta_e':0.3045,   //First Order  Longitudinal Derivative Coefficient of aeleron deflecion to Calculate Drag Coefficient    
                'm_delta_e':-0.3254,  //First Order  Longitudinal Derivative Coefficient of aeleron deflecion to Calculate Torque Coefficient
                'prop':1.0,           //Properller Coefficient
                'D_p':0.0254,         //Parasitic Drag Coefficient
                'Y_0':0,              //Zeroth Order Lateral Force Coefficient
                'l_0':0,              //Zeroth Order Roll Moment Coefficient
                'n_0':0,              //Zeroth Order Yaw Moment Coefficient
                'Y_beta':-0.07359,    //First Order Lateral Force Coefficient of Slip Angle Beta
                'l_beta':-0.02854,    //First Order Roll Moment Coefficient of Slip Angle Beta
                'n_beta':-0.00040,    //First Order Yaw Moment Coefficient of Slip Angle Beta
                'Y_p':0,              //First Order Lateral Force Coefficient of Roll Rate p
                'l_p':-0.3209,        //First Order Roll Moment Coefficient of Roll Rate p
                'n_p':-0.01297,       //First Order Yaw Moment Coefficient of Roll Rate p
                'Y_r':0,              //First Order Lateral Force Coefficient of Yaw Rate r
                'l_r':0.03066,        //First Order Roll Moment Coefficient of Yaw Rate r
                'n_r':-0.00434,       //First Order Yaw Moment Coefficient of Yaw Rate r
                'Y_delta_a':0,        //First Order Lateral Force Coefficient of aeleron defelction delta_a
                'l_delta_a':0.1682,   //First Order Roll Moment Coefficient of aeleron defelction delta_a
                'n_delta_a':-0.00328, //First Order Yaw Moment Coefficient of aeleron defelction delta_a
                'Y_delta_r':0,        //First Order Lateral Force Coefficient of rudder defelction delta_r
                'l_delta_r':0         //First Order Roll Moment Coefficient of rudder defelction delta_r
            },
            'M':50,                   //Sigmoid Function Transition Rate Coefficient (Positive) of Angle of Attack
            'alpha_0':0.4712,         //Sigmoid Function Cut-off Angle of Attack Coefficient(Positive)
            'epsilon':0.1592
        },
        {
            'name': 'Aerosonode',
            'mass': 13.5,             // kg
            'V_s': 18.8951,           // m/s
            'J_vector':               //vector of elements in the Intertial Matrix
            {
                'x':0.8244,           //J_x or J_xx (Kg m^2)
                'y':1.135,            //J_y or J_yy (Kg m^2)
                'z':1.759,            //J_z or J_zz (Kg m^2)
                'xz':0.1204           //J_xz (Kg m^2)
            },
            'S':0.55,                 //Surface area of the wing (m^2)
            'b':2.8956,               //Wing span (m)
            'c':0.18994,              //Mean aerodynamic chord of the wing (m)
            'S_prop':0.2027,          //Area of the propeller (m^2)
            'k_motor':80,             //Constant that specifies the efficiency of the motor
            'k_T_p':0,                //Constant determined experiment to determine the torque generated by propellor at different prop angular speeds
            'k_Omega':0,              //Constant to convert prop motor PWM commands to Prop Angular Speed
            'e':0.9,                                                           
            'C_arr':                                                           
            {                                                           
                'L_0':0.28,           //Zeroth Order Longitudinal Derivative Coefficient of Alpha the Angle of Attack to Calculate Lift Coefficient
                'D_0':0.03,           //Zeroth Order Longitudinal Derivative Coefficient of Alpha the Angle of Attack to Calculate Drag Coefficient
                'm_0':-0.02338,       //Zeroth Order Longitudinal Derivative Coefficient of Alpha the Angle of Attack to Calculate Torque Coefficient
                'L_alpha':3.45,       //First Order Longitudinal  Derivative Coefficient of Alpha the Angle of Attack to Calculate Lift Coefficient
                'D_alpha':0.30,       //First Order Longitudinal  Derivative Coefficient of Alpha the Angle of Attack to Calculate Drag Coefficient
                'm_alpha':-0.38,      //First Order Longitudinal  Derivative Coefficient of Alpha the Angle of Attack to Calculate Torque Coefficient
                'L_q':0,              //First Order  Longitudinal Derivative Coefficient of Pitch Rate to Calculate Lift Coefficient
                'D_q':0,              //First Order  Longitudinal Derivative Coefficient of Pitch Rate to Calculate Drag Coefficient    
                'm_q':-3.6,           //First Order  Longitudinal Derivative Coefficient of Pitch Rate to Calculate Torque Coefficient
                'L_delta_e':-0.36,    //First Order  Longitudinal Derivative Coefficient of aeleron deflecion to Calculate Lift Coefficient
                'D_delta_e':0,        //First Order  Longitudinal Derivative Coefficient of aeleron deflecion to Calculate Drag Coefficient    
                'm_delta_e':-0.5,     //First Order  Longitudinal Derivative Coefficient of aeleron deflecion to Calculate Torque Coefficient
                'prop':1.0,           //Properller Coefficient
                'D_p':0.0437,         //Parasitic Drag Coefficient
                'n_delta_r':-0.032,   //Coefficient of n moment caused by rudder deflection
                'Y_0':0,              //Zeroth Order Lateral Force Coefficient
                'l_0':0,              //Zeroth Order Roll Moment Coefficient
                'n_0':0,              //Zeroth Order Yaw Moment Coefficient
                'Y_beta':-0.98,       //First Order Lateral Force Coefficient of Slip Angle Beta
                'l_beta':-0.12,       //First Order Roll Moment Coefficient of Slip Angle Beta
                'n_beta':0.25,        //First Order Yaw Moment Coefficient of Slip Angle Beta
                'Y_p':0,              //First Order Lateral Force Coefficient of Roll Rate p
                'l_p':-0.26,          //First Order Roll Moment Coefficient of Roll Rate p
                'n_p':0.022,          //First Order Yaw Moment Coefficient of Roll Rate p
                'Y_r':0,              //First Order Lateral Force Coefficient of Yaw Rate r
                'l_r':0.14,           //First Order Roll Moment Coefficient of Yaw Rate r
                'n_r':-0.35,          //First Order Yaw Moment Coefficient of Yaw Rate r
                'Y_delta_a':0,        //First Order Lateral Force Coefficient of aeleron defelction delta_a
                'l_delta_a':0.08,     //First Order Roll Moment Coefficient of aeleron defelction delta_a
                'n_delta_a':0.06,     //First Order Yaw Moment Coefficient of aeleron defelction delta_a
                'Y_delta_r':-0.17,    //First Order Lateral Force Coefficient of rudder defelction delta_r
                'l_delta_r':0.105     //First Order Roll Moment Coefficient of rudder defelction delta_r
            },
            'M':50,                   //Sigmoid Function Transition Rate Coefficient (Positive) of Angle of Attack
            'alpha_0':0.4712,         //Sigmoid Function Cut-off Angle of Attack Coefficient(Positive)
            'epsilon':0.1592
        },
        {
            'name': 'Gemini'
        }
    ]
}

const g = 9.8;  //Acceleration Due To Gravity (m/s)
const rho = 1.2682;  // Air Density (Kg/m^3)

module.exports = {uav_param_config, g, rho};